### ISSUE TITLE
Add the live website to the repo (in about or "website")

### ISSUE THREAD

**Issue by tippi-fifestarr** [cromewar/World-of-Hackathon-Wingbirds#33]
It's also not easily accessible via our demo video...

**Comment by cromewar** [comment]
I'll get it done

**Comment by tippi-fifestarr** [comment]
![image](https://user-images.githubusercontent.com/62179036/152232807-bd28dfc2-3763-4f70-acbc-829b93174272.png)
cool, yeah it will just show up here on the right side under "website".
on my fork I have it going to the github pages so its easy to find: 
![image](https://user-images.githubusercontent.com/62179036/152232950-8a534d73-c805-4575-9978-7686a2e4b6b6.png)

**Comment by tippi-fifestarr** [comment]
Just click the little "settings gear" over there in the top right.

**Comment by tippi-fifestarr** [comment]
@cromewar did it, and I added links in comments to our YouTube Demo Video
